# Generated by Django 4.0.6 on 2023-03-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('event_host', models.CharField(blank=True, max_length=250, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_location', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Events_images')),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='leaders')),
                ('year_start', models.DateField()),
                ('year_end', models.DateField()),
                ('whatsapp_number', models.CharField(max_length=11)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(max_length=128)),
                ('state_of_origin', models.CharField(max_length=64)),
                ('local_govt', models.CharField(max_length=64)),
                ('residential_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('prayer_topic', models.CharField(max_length=250)),
                ('phone_numbers', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('answered', 'Answered '), ('pending', 'Pending'), ('processing', 'Processing')], default='Pending', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('miracle', models.TextField()),
                ('photo', models.ImageField(upload_to='testimony')),
            ],
        ),
    ]
